export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGES = 'DELETE_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_CHAT = 'ADD_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';
export const GET_GITDATA = 'GET_GITDATA';
export const LOADING_GITDATA  = 'LOADING_GITDATA';
export const ERROR_GITDATA = 'ERROR_GITDATA';
