
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGES = 'DELETE_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_CHAT = 'ADD_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';

export const LOADING_GITDATA  = 'LOADING_GITDATA';
export const GET_GITDATA = 'GET_GITDATA';
export const ERROR_GITDATA = 'ERROR_GITDATA';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';